# Dependencies
markdown:         redcarpet
# highlighter:      pygments
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /tjcompsci.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

plugins: 		 

- jekyll-paginate 
- jekyll-gist


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


