# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# highlighter:      pygments
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            TJ CompSci
tagline:          'All things CS @ TJHSST'
description:      'All things CS @ TJHSST'
url:              http://tjcompsci.github.io
baseurl:          /


author:
  name:           'Ria Galanos'
  url:            https://twitter.com/cscheerleader

plugins: 		 

- jekyll-paginate 
- jekyll-gist


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


